swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport : gmail
    host: smtp.gmail.com
    port: 465
    auth_mode: login
    username: horizons.appli5@gmail.com
    password: horizons2020
    encryption: ssl
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false